### ISSUE TITLE
How to switch front camera to back ? 

### ISSUE THREAD

**Issue by gersonjanhuel** [Rainbow-CPaaS/Rainbow-iOS-SDK-Samples#1]
Hi 

I've been using rainbow webRTC framework before, after update the to Rainbow sdk 1.46.0 
my code to switch camera doesn't work anymore : 

`

> if localVideoTrack != nil {
> 
>    if let source = localVideoTrack.source as? RTCAVFoundationVideoSource {
>         source.useBackCamera = isRearCameraActive
>         self.localVideoView.captureSession = source.captureSession
>       }
>     }

`

RTCAVFoundationVideoSource is deprecated. How to work around with this ?

**Comment by vyskocil** [comment]
The WebRTC sample app has been updated accordingly to the latest changes : https://github.com/Rainbow-CPaaS/Rainbow-iOS-SDK-Samples/tree/master/Rainbow-iOS-SDK-Sample-WebRTC

**Comment by vyskocil** [comment]
Hi Gerson,

Due to the WebRTC stack update in the latest iOS Rainbow SDK, which has deprecated RTCAVFoundationVideoSource, the local video part has to be updated with the new provided class : RTCCameraVideoCapturer

The sample app has been updated accordingly : 
https://github.com/Rainbow-CPaaS/Rainbow-iOS-SDK-Samples/tree/master/Rainbow-iOS-SDK-Sample-WebRTC

**Comment by gersonjanhuel** [comment]
I got error :  Symbol not found: _kRTCServiceDidAddCaptureSessionNotification

**Comment by gersonjanhuel** [comment]
@vyskocil
